import { useCallback, useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { billingApi } from "../../api/billingApi";
import { useAuth } from "../../hooks/useAuth";
import PaymentModal from "../../components/billing/PaymentModal";
import RefundModal from "../../components/billing/RefundModal";
import InsuranceClaimPanel from "../../components/billing/InsuranceClaimPanel";
import StatusBadge from "../../components/common/StatusBadge";
const TONE = { PENDING: "warning", PARTIALLY_PAID: "warning", PAID: "success", CANCELLED: "neutral" };
export default function BillDetailPage() { const { id } = useParams(); const { user } = useAuth(); const canManage = user?.roles?.some((role) => ["ROLE_ADMIN", "ROLE_PHARMACIST"].includes(role)); const [bill, setBill] = useState(null); const [error, setError] = useState(""); const [modal, setModal] = useState(null); const [forbidden, setForbidden] = useState(false); const load = useCallback(async () => { try { const response = await billingApi.getById(id); setBill(response.data.data); } catch (err) { if ([403, 404].includes(err.response?.status)) setForbidden(true); else setError(err.response?.data?.message || "Could not load bill."); } }, [id]); useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]); async function cancel() { try { await billingApi.cancel(id); load(); } catch (err) { setError(err.response?.data?.message || "Could not cancel bill."); } } if (forbidden) return <main className="detail-page"><p className="form-error">This bill is not available to you.</p></main>; if (error && !bill) return <main className="detail-page"><p className="form-error">{error}</p></main>; if (!bill) return <main className="detail-page">Loading...</main>; return <main className="detail-page"><h1>Bill #{bill.id}</h1><p className="detail-page__meta">{bill.patientName}</p><StatusBadge label={bill.status || "UNKNOWN"} tone={TONE[bill.status] || "neutral"} /><table className="data-table bill-breakdown"><tbody>{[["Subtotal", bill.subtotal], ["Dispensing fee", bill.dispensingFee], ["Discount", bill.discountAmount], ["GST", bill.taxAmount], ["Total", bill.totalAmount], ["Insurance covered", bill.insuranceAmount], ["Co-payment", bill.coPayment], ["Paid", bill.amountPaid], ["Refunded", bill.amountRefunded], ["Outstanding", bill.outstandingAmount]].map(([label, value]) => <tr key={label}><td>{label}</td><td>{value}</td></tr>)}</tbody></table>{error && <p className="form-error">{error}</p>}{canManage && bill.status !== "CANCELLED" && <div className="header-actions"><button type="button" onClick={() => setModal("payment")}>Record payment</button><button type="button" onClick={() => setModal("refund")}>Record refund</button>{bill.status === "PENDING" && <button type="button" onClick={cancel}>Cancel bill</button>}</div>}<InsuranceClaimPanel bill={bill} onUpdated={load} />{modal === "payment" && <PaymentModal billId={bill.id} onClose={() => setModal(null)} onSaved={() => { setModal(null); load(); }} />}{modal === "refund" && <RefundModal billId={bill.id} onClose={() => setModal(null)} onSaved={() => { setModal(null); load(); }} />}</main>; }
