import { useCallback, useEffect, useState } from "react";
import { systemAdminApi } from "../../api/systemAdminApi"; import { drugApi } from "../../api/drugApi"; import { reportApi } from "../../api/reportApi"; import { purchaseOrderApi } from "../../api/purchaseOrderApi"; import { useAuth } from "../../hooks/useAuth";
import StatCard from "../../components/dashboard/StatCard"; import TrendAreaChart from "../../components/dashboard/TrendAreaChart"; import DonutChart from "../../components/dashboard/DonutChart"; import BarChartCard from "../../components/dashboard/BarChartCard";
const labels = { OTC: "OTC", SCHEDULE_H: "Schedule H", SCHEDULE_H1: "Schedule H1", SCHEDULE_X: "Schedule X" };
const rowsOf = (data) => data?.content || data || [];
export default function AdminDashboard() { const { user } = useAuth(); const [health, setHealth] = useState(null); const [reorderCount, setReorderCount] = useState(null); const [volume, setVolume] = useState([]); const [schedule, setSchedule] = useState([]); const [spend, setSpend] = useState([]); const [error, setError] = useState("");
  const load = useCallback(async () => { const results = await Promise.allSettled([systemAdminApi.getSystemHealth(), purchaseOrderApi.getReorderSuggestions(), reportApi.getPrescriptionVolume({}), drugApi.list({ page: 0, size: 500, activeOnly: true }), reportApi.getProcurementSpending({})]); const [h, r, v, d, s] = results; if (h.status === "fulfilled") setHealth(h.value.data.data); if (r.status === "fulfilled") setReorderCount(rowsOf(r.value.data.data).length); if (v.status === "fulfilled") setVolume(rowsOf(v.value.data.data).map((row) => ({ label: row.date, value: row.prescriptionCount }))); if (d.status === "fulfilled") { const counts = {}; rowsOf(d.value.data.data).forEach((row) => { counts[row.schedule] = (counts[row.schedule] || 0) + 1; }); setSchedule(Object.entries(counts).map(([name, value]) => ({ name: labels[name] || name, value }))); } if (s.status === "fulfilled") setSpend(rowsOf(s.value.data.data).slice(0, 6).map((row) => ({ label: row.supplierName, value: row.totalSpend }))); if (results.every((result) => result.status === "rejected")) setError("Could not load dashboard data."); }, []);
  useEffect(() => { load(); const interval = setInterval(load, 60000); return () => clearInterval(interval); }, [load]);
  return <main className="dashboard-page"><div className="dashboard-page__header"><h1>Admin overview</h1><p>Welcome back, {user?.fullName || user?.name || user?.staffId}.</p></div>{error && <p className="form-error">{error}</p>}<div className="stat-grid"><StatCard label="Prescription queue" value={health?.pendingPrescriptionQueueCount} /><StatCard tone="violet" label="Low-stock drugs" value={health?.lowStockDrugCount} /><StatCard tone="amber" label="Reorder alerts" value={reorderCount} /><StatCard tone="emerald" label="Total active users" value={health?.activeUsers} /></div><div className="chart-grid"><TrendAreaChart title="Prescription volume" subtitle="Recent activity" data={volume} /><DonutChart title="Drugs by schedule" data={schedule} /></div><div className="chart-grid chart-grid--single"><BarChartCard title="Procurement spend by supplier" data={spend} color="#8b5cf6" /></div></main>; }
