export const ROLE_NAV_GROUPS = {
  ROLE_ADMIN: [
    { label: "Overview", items: [{ label: "Dashboard", to: "/dashboard/admin" }] },
    { label: "Patients & Care", items: [{ label: "Patients", to: "/patients" }, { label: "Doctors", to: "/doctors" }] },
    { label: "Pharmacy", items: [{ label: "Drugs", to: "/drugs" }, { label: "Interactions", to: "/drugs/interactions" }, { label: "Inventory", to: "/inventory" }] },
    { label: "Controlled Substances", items: [{ label: "CS Register", to: "/controlled-substances/register" }] },
    { label: "Procurement", items: [{ label: "Suppliers", to: "/suppliers" }, { label: "Purchase Orders", to: "/purchase-orders" }, { label: "GRN", to: "/grn" }] },
    { label: "Billing", items: [{ label: "Generate Bill", to: "/bills/new" }, { label: "Outstanding Bills", to: "/bills/outstanding" }] },
    { label: "Reports", items: [{ label: "Reports", to: "/reports" }] },
    { label: "Administration", items: [{ label: "Audit Logs", to: "/admin/audit-logs" }, { label: "Users", to: "/admin/users" }, { label: "Config", to: "/admin/config" }, { label: "Shifts", to: "/admin/shifts" }, { label: "Holidays", to: "/admin/holidays" }, { label: "Operating Hours", to: "/admin/operating-hours" }, { label: "System Health", to: "/admin/system-health" }, { label: "Compliance", to: "/admin/compliance" }] },
  ],
  ROLE_PHARMACIST: [{ label: "Overview", items: [{ label: "Dashboard", to: "/dashboard/pharmacist" }] }, { label: "Patients & Care", items: [{ label: "Patients", to: "/patients" }, { label: "Doctors", to: "/doctors" }] }, { label: "Pharmacy", items: [{ label: "Drugs", to: "/drugs" }, { label: "Inventory", to: "/inventory" }] }, { label: "Dispensing", items: [{ label: "Prescription Queue", to: "/prescriptions/queue" }, { label: "Dispensing", to: "/dispensing" }] }, { label: "Controlled Substances", items: [{ label: "CS Register", to: "/controlled-substances/register" }] }, { label: "Procurement", items: [{ label: "GRN", to: "/grn" }] }, { label: "Billing", items: [{ label: "Generate Bill", to: "/bills/new" }, { label: "Outstanding Bills", to: "/bills/outstanding" }] }],
  ROLE_TECHNICIAN: [{ label: "Overview", items: [{ label: "Dashboard", to: "/dashboard/technician" }] }, { label: "Patients & Care", items: [{ label: "Patients", to: "/patients" }] }, { label: "Dispensing", items: [{ label: "Prescription Queue", to: "/prescriptions/queue" }] }, { label: "Pharmacy", items: [{ label: "Inventory", to: "/inventory" }] }],
  ROLE_PROCUREMENT_OFFICER: [{ label: "Overview", items: [{ label: "Dashboard", to: "/dashboard/procurement" }] }, { label: "Pharmacy", items: [{ label: "Inventory", to: "/inventory" }] }, { label: "Procurement", items: [{ label: "Suppliers", to: "/suppliers" }, { label: "Purchase Orders", to: "/purchase-orders" }, { label: "GRN", to: "/grn" }] }],
  ROLE_AUDITOR: [{ label: "Overview", items: [{ label: "Dashboard", to: "/dashboard/auditor" }] }, { label: "Pharmacy", items: [{ label: "Inventory", to: "/inventory" }] }, { label: "Reports", items: [{ label: "Reports", to: "/reports" }] }, { label: "Administration", items: [{ label: "Audit Logs", to: "/admin/audit-logs" }, { label: "Compliance", to: "/admin/compliance" }] }],
  ROLE_DOCTOR: [{ label: "Overview", items: [{ label: "Dashboard", to: "/dashboard/doctor" }] }, { label: "My Work", items: [{ label: "My Profile", to: "/doctors/me" }, { label: "New Prescription", to: "/prescriptions/new" }, { label: "My Prescriptions", to: "/prescriptions/my" }] }],
  ROLE_PATIENT: [{ label: "Overview", items: [{ label: "Dashboard", to: "/dashboard/patient" }] }, { label: "My Account", items: [{ label: "My Profile", to: "/patients/me" }, { label: "My Prescriptions", to: "/prescriptions/my" }, { label: "My Bills", to: "/bills/my" }] }],
};
