import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { prescriptionApi } from "../../api/prescriptionApi";

export default function PrescriptionSubmitPage() {
  const navigate = useNavigate(); const [form, setForm] = useState({ patientId: "", source: "ELECTRONIC", digitalSignature: "", items: [{ drugId: "", quantity: "", dosageInstructions: "", refillsAllowed: 0 }] }); const [error, setError] = useState("");
  function updateItem(index, field, value) { setForm((prev) => ({ ...prev, items: prev.items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) })); }
  async function submit(event) { event.preventDefault(); try { await prescriptionApi.create({ ...form, digitalSignature: form.source === "ELECTRONIC" ? form.digitalSignature : undefined }); navigate("/prescriptions/my"); } catch (err) { setError(err.response?.data?.message || "Couldn't submit prescription."); } }
  return <main className="detail-page"><h1>New prescription</h1><form className="modal-form modal-form--standalone" onSubmit={submit}><label>Patient ID<input value={form.patientId} onChange={(event) => setForm({ ...form, patientId: event.target.value })} required /></label><label>Source<select value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value })}><option>ELECTRONIC</option><option>VERBAL</option><option>WRITTEN</option></select></label>{form.source === "ELECTRONIC" && <label>Digital signature<input value={form.digitalSignature} onChange={(event) => setForm({ ...form, digitalSignature: event.target.value })} required /></label>}<h2>Items</h2>{form.items.map((item, index) => <div className="prescription-item-row" key={index}><input placeholder="Drug ID" value={item.drugId} onChange={(event) => updateItem(index, "drugId", event.target.value)} required /><input type="number" placeholder="Qty" value={item.quantity} onChange={(event) => updateItem(index, "quantity", event.target.value)} required /><input placeholder="Dosage instructions" value={item.dosageInstructions} onChange={(event) => updateItem(index, "dosageInstructions", event.target.value)} required /></div>)}{error && <p className="form-error">{error}</p>}<button type="submit">Submit prescription</button></form></main>;
}
