package com.pharmacy.pipms.notification.entity;

public enum NotificationType {
    LOW_STOCK, NEAR_EXPIRY, EXPIRED_STOCK,
    PRESCRIPTION_RECEIVED, PRESCRIPTION_VERIFIED, PRESCRIPTION_REJECTED, PRESCRIPTION_READY,
    CONTROLLED_SUBSTANCE_DISCREPANCY,
    PURCHASE_ORDER_APPROVAL, PURCHASE_ORDER_DELIVERY,
    LICENSE_RENEWAL, SYSTEM_MAINTENANCE, COLD_CHAIN_BREACH,
    ESCALATION
}